In [24]:
# A Quick Primer on Numpy

import numpy as np

In [25]:
# A vector
a=np.array([0,1,2,3])
print a
print a.shape
print a.T.shape

[0 1 2 3]
(4,)
(4,)


In [26]:
#Another Vector
b=np.array([4,5,6,7])
print b

[4 5 6 7]


In [27]:
# A matrix
# One row of a matrix is a vector
c=np.array([[0,1,2,3],[4,5,6,7]])
print c

[[0 1 2 3]
 [4 5 6 7]]


In [28]:
# 2*4 matrix of zeros

d=np.zeros((2,4))
print d

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [29]:
# Random 2*5

e=np.random.rand(2,5)
print e

[[ 0.04555409  0.99473567  0.06570582  0.77233308  0.84723809]
 [ 0.69646592  0.60402965  0.14950007  0.4776117   0.31218472]]


In [30]:
# Multiplies every number in a vector
print a*0.1

[ 0.   0.1  0.2  0.3]


In [31]:
# Multiplies every number in a matrix
print c*0.2

[[ 0.   0.2  0.4  0.6]
 [ 0.8  1.   1.2  1.4]]


In [32]:
# Multiplies elementwise between a and b
print a*b

[ 0  5 12 21]


In [33]:
# Since c has the same number of columns as a, this performs elementwise multiplication on every row of the matrix 'c
print a*c

[[ 0  1  4  9]
 [ 0  5 12 21]]


In [34]:
# Since a and e don't have the same number of columns,this throws a 'Value Error'

print a*e

ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [40]:
# The general rule of thumb for anything elementwise (+,-,*,/) is that the two variables must either have the SAME 
# number of columns, or one of the variables must only have 1 column

a=np.zeros((1,4))
b=np.zeros((4,3))
print a
print
print b

c=a.dot(b)

print
print c
print
print c.shape



[[ 0.  0.  0.  0.]]

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 0.  0.  0.]]

(1, 3)


In [ ]:
# There is one golden rule when using the 'dot' function. If you put the (rows,cols) de- scription of the two variables
# you're "dotting" next to each other, neighboring numbers should always be the same. In this case, we're dot producting 
# a (1,4) with a (4,3).  us, it works  ne, and outputs a (1,3). In terms of variable shape, you can think of it this way. 
# Regardless of wheth- er you're "dotting" vectors or matrices.  eir "shape"(number of rows and columns) must line up. 
#The col-umns on the "le " matrix must equal rows on the "right".

In [41]:
a=np.zeros((2,4))
b=np.zeros((4,3))

c=a.dot(b)

print c.shape

(2, 3)


In [42]:
e=np.zeros((2,1))
f=np.zeros((1,3))

g=e.dot(f)
print g.shape

(2, 3)


In [43]:
h=np.zeros((5,4)).T
print h

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [44]:
i=np.zeros((5,6))
j=h.dot(i)

print j.shape

(4, 6)


In [45]:
h=np.zeros((5,4))
i=np.zeros((5,6))

j=h.dot(i)

print j.shape

ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)