In [73]:
# Initialize the network's weights and data

import numpy as np
np.random.seed(1)

def relu(x):
    return (x>0) *x

def relu2deriv(output):
    return output>0


In [74]:
lights=np.array([[1,0,1],
                [0,1,1],
                [0,0,1],
                [1,1,1]])
walk_stop=np.array([[1,1,0,0]]).T
print walk_stop
alpha=0.2
hidden_size=3
weight_0_1=2*np.random.random((3,hidden_size))-1
print weight_0_1
weight_1_2=2*np.random.random((hidden_size,1))-1
print weight_1_2

[[1]
 [1]
 [0]
 [0]]
[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]]
[[ 0.07763347]
 [-0.16161097]
 [ 0.370439  ]]


In [75]:
# Predict & compare: make a prediction, calculate output error and delta

layer_0=lights[0:1]
print layer_0
layer_1=np.dot(layer_0,weight_0_1)
print layer_1
layer_1=relu(layer_1)
print layer_1

layer_2=np.dot(layer_1,weight_1_2)
print layer_2

error=(layer_2-walk_stop[0:1])**2
print error

layer_2_delta=(layer_2-walk_stop[0:1])
print layer_2_delta

[[1 0 1]]
[[-0.79343557  0.13177044 -1.2062363 ]]
[[-0.          0.13177044 -0.        ]]
[[-0.02129555]]
[[ 1.0430446]]
[[-1.02129555]]


In [76]:
print layer_2.shape
print weight_1_2.shape

(1, 1)
(3, 1)


In [77]:
layer_1_delta=layer_2.dot(weight_1_2.T)
layer_1_delta=relu2deriv(layer_1)
print layer_1_delta

[[False  True False]]


In [82]:
# Learn: Generate weight deltas and update weights
print layer_1.shape
print layer_2_delta.shape

weight_delta_1_2=layer_1.T.dot(layer_2_delta)
print weight_delta_1_2

weight_delta_0_1=layer_0.T.dot(layer_1_delta)
print weight_delta_0_1

weight_1_2-=alpha*weight_delta_1_2
print weight_1_2

weight_0_1-=alpha*weight_delta_0_1
print weight_0_1

(1, 3)
(1, 1)
[[ 0.        ]
 [-0.13457656]
 [ 0.        ]]
[[0 1 0]
 [0 0 0]
 [0 1 0]]
[[ 0.07763347]
 [-0.10778035]
 [ 0.370439  ]]
[[-0.16595599  0.04064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.70887855 -0.20646505]]
